# Generated by Django 4.1.7 on 2023-05-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
