# Generated by Django 4.1.7 on 2023-06-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_foodcategory_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
