# Generated by Django 4.1.4 on 2023-05-03 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None)),
                ('size', models.CharField(default='medium', max_length=128)),
                ('id_food', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.food')),
                ('id_userdata', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userphoto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userright',
            name='id_right',
        ),
        migrations.RemoveField(
            model_name='userright',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='date_update',
        ),
        migrations.DeleteModel(
            name='Right',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
        migrations.DeleteModel(
            name='UserRight',
        ),
    ]
