# Generated by Django 4.1.7 on 2023-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('new', 'Не принят в обработку'), ('cancel', 'Отменен'), ('start', 'Принят в обработку'), ('cooking', 'Готовят'), ('ready', 'Заказ готов'), ('success', 'Заказ завершен')], default='new', max_length=128),
        ),
    ]
